### ISSUE TITLE
63 bits is not enough to encode CAP amounts

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cap#37]
As mentioned in , in practice ERC20 tokens for example may have 18 decimals which means a single unit of this token corresponds already to a number in the range of 10**19 > 2**63.

Change the circuit in order to handle amounts that can be encoded at least with 128 bits.

**Comment by philippecamacho** [comment]
Once #43 is merged we will need to regenerate the verification keys right before redeploying the contract right? @alxiong @chancharles92

**Comment by chancharles92** [comment]
> Once #43 is merged we will need to regenerate the verification keys right before redeploying the contract right? @alxiong @chancharles92

Yes I think so. Hi Alex @alxiong , can you help with this question?

**Comment by alxiong** [comment]
No I don't think we need to regenerate the VK. Since the circuit has never changed? Amount type doesn't affect its representation as a field element (which is 254 bit)

**Comment by chancharles92** [comment]
> No I don't think we need to regenerate the VK. Since the circuit has never changed? Amount type doesn't affect its representation as a field element (which is 254 bit)

`AMOUNT_LEN` changed, so circuits will also be changed.

**Comment by alxiong** [comment]
oh yes, you are right, I missed that. Agree that we need to regenerate VK and redeploy contracts. @philippecamacho

**Comment by philippecamacho** [comment]
Thanks @alxiong  & @chancharles92 !
 @alxiong  so regenerate the VK is done by running [cargo run --bin gen-vk-libraries --release](https://github.com/EspressoSystems/cape/blob/62dd8aee97e1ef16c3b92f022f3333881a8f6b9c/contracts/contracts/libraries/Freeze2In2Out24DepthVk.sol#L10) , right?
 cc @sveitser
